VPD TOOL : Fix Broken ECC
Vpd tool has another option called Fix Broken ECC
which fixes the broken 1-bit ECC. If more than 1-bit is
broken, then it is an UNCORRECTABLE ERROR.

Input: Expects the object path & the record where the ecc fails.
Output: Fixes the ecc and writes back the corrected file in EEPROM.

Test:
Tested in rainier104bmc and rainier2bmc.

Corrupt the vpd at a certain record

root@rain104bmc:/tmp# ibm-read-vpd --file /sys/devices/platform/ahb/ahb:apb/1e79b000.fsi/fsi-master/fsi0/slave@00:00/00:00:00:0a/fsi-master/fsi1/slave@01:00/01:01:00:04/spi_master/spi22/spi22.0/spi22.00/nvmem
Power state is: xyz.openbmc_project.State.Chassis.PowerState.Off
ERROR: ECC check did not pass for the Record:VINI
root@rain104bmc:/tmp#

root@rain104bmc:/tmp# ./vpd-tool --eccFix --object /system/chassis/motherboard/cpu1 --record VINI
ECC updation successfull for the given record VINI ,present in the given object /system/chassis/motherboard/cpu1.

root@rain104bmc:/tmp# ibm-read-vpd --file /sys/devices/platform/ahb/ahb:apb/1e79b000.fsi/fsi-master/fsi0/slave@00:00/00:00:00:0a/fsi-master/fsi1/slave@01:00/01:01:00:04/spi_master/spi22/spi22.0/spi22.00/nvmem
Power state is: xyz.openbmc_project.State.Chassis.PowerState.Off
root@rain104bmc:/tmp#

Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>
Change-Id: I52b3bc70a9b2d85863b472a1d96e4f131ebdb94e