vpd-tool:Fix ECC option
Vpd tool has an added option for fixing the broken ECC,
given the object path and the record for which the ecc
needs to be fixed.

The api assumes the record data is correct and fixes the ECC
accordingly.

Input: Expects the object path & the record where the ecc fails.
Output: Fixes the ecc and writes back the corrected file in EEPROM.

Test:
Tested on simics
Modify/update the vpd at a certain record and run eccFix Tool option.
The ecc of the record is updated assuming the updated record value
is correct.

root@rain135bmc:/tmp# dd if=/dev/zero of=/sys/bus/i2c/drivers/at24/7-0050/eeprom bs=1 seek=276 count=1
1+0 records in
1+0 records out

root@rain135bmc:/tmp# ibm-read-vpd --file /sys/bus/i2c/drivers/at24/7-0050/eeprom
ERROR: ECC check did not pass for the Record:VR10
root@rain135bmc:/tmp# ./vpd-tool -e --object /system/chassis/motherboard/base_op_panel_blyth --record VR10

 ECC updation successfull for the given record VR10 ,present in the given object /system/chassis/motherboard/base_op_panel_blyth.
root@rain135bmc:/tmp#
root@rain135bmc:/tmp# ibm-read-vpd --file /sys/bus/i2c/drivers/at24/7-0050/eeprom

Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>
Change-Id: Icfcfb4a8f4b88563d3bae36c104c8a85bccf0283