VPD ECC EXCEPTION:Supports additional data
The vpd ecc exception class now throws the failed record data,
the failed ecc data and the failed record name for failure analysis.

Modified Impl class according to the ecc exception class.

Modified ibm-read-vpd according to the ecc exception class.

Tested on simics:

Corrupt the vpd

root@rainier:/tmp# dd if=/dev/zero of=/sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a500.i2c-bus/i2c-9/9-0050/9-00500/nvmem bs=1 skip=0 count=1 seek=174
1+0 records in
1+0 records out
root@rainier:/tmp#

root@rainier:/tmp# ./ibm-read-vpd --file /sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a500.i2c-bus/i2c-9/9-0050/9-00500/nvmem
ERROR: ECC check did not pass for the Record:VINI

root@rainier:/tmp# peltool -l
{
	"0x50000001": {
		"SRC": "BD554002",
		"Message": "A VPD ecc exception occurred.",
		"PLID": "0x50000001",
		"CreatorID": "BMC",
		"Subsystem": "CEC Hardware: VPD Interface",
		"Commit Time": "03/06/2021 18:05:20",
		"Sev": "Unrecoverable Error",
 		"CompID": "0x4000"
 	}
}

root@rainier:/tmp# peltool -i 50000001
{
"Private Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x4000",
    "Created at":               "03/06/2021 18:05:20",
    "Committed at":             "03/06/2021 18:05:20",
    "Creator Subsystem":        "BMC",
    "CSSVER":                   "",
    "Platform Log Id":          "0x50000001",
    "Entry Id":                 "0x50000001",
    "BMC Event Log Id":         "1"
},
"User Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Log Committed by":         "0x2000",
    "Subsystem":                "CEC Hardware: VPD Interface",
    "Event Scope":              "Entire Platform",
    "Event Severity":           "Unrecoverable Error",
    "Event Type":               "Not Applicable",
    "Action Flags": [
                                "Service Action Required",
                                "Report Externally",
                                "HMC Call Home"
    ],
    "Host Transmission":        "Not Sent"
},
"Primary SRC": {
    "Section Version":          "1",
    "Sub-section type":         "1",
    "Created by":               "0x4000",
    "SRC Version":              "0x02",
    "SRC Format":               "0x55",
    "Virtual Progress SRC":     "False",
    "I5/OS Service Event Bit":  "False",
    "Hypervisor Dump Initiated":"False",
    "Power Control Net Fault":  "False",
    "Backplane CCIN":           "2E2D",
    "Deconfigured":             "False",
    "Guarded":                  "False",
    "Error Details": {
        "Message":              "A VPD ecc exception occurred."
    },
    "Valid Word Count":         "0x09",
    "Reference Code":           "BD554002",
    "Hex Word 2":               "00000055",
    "Hex Word 3":               "2E2D0010",
    "Hex Word 4":               "00000000",
    "Hex Word 5":               "00000000",
    "Hex Word 6":               "00000000",
    "Hex Word 7":               "00000000",
    "Hex Word 8":               "00000000",
    "Hex Word 9":               "00000000",
    "Callout Section": {
        "Callout Count":        "1",
        "Callouts": [{
            "FRU Type":         "Normal Hardware FRU",
            "Priority":         "Mandatory, replace all with this type as a unit",
            "Location Code":    "U78DA.ND0.1234567-P0-C14",
            "Part Number":      "F190827",
            "CCIN":             "2E32",
            "Serial Number":    "qL2E32010000"
        }]
    }
},
"Extended User Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x2000",
    "Reporting Machine Type":   "9105-22A",
    "Reporting Serial Number":  "SIMP10R",
    "FW Released Ver":          "",
    "FW SubSys Version":        "fw1020.00-16.0",
    "Common Ref Time":          "00/00/0000 00:00:00",
    "Symptom Id Len":           "20",
    "Symptom Id":               "BD554002_2E2D0010"
},
"Failing MTMS": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x2000",
    "Machine Type Model":       "9105-22A",
    "Serial Number":            "SIMP10R"
},
"User Data 0": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "BMC Version ID": "fw1020.00-16.0-dirty",
    "BMCState": "Ready",
    "ChassisState": "Off",
    "HostState": "Off",
    "Process Name": "Unknown"
},
"User Data 1": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "CALLOUT_INVENTORY_PATH": "/xyz/openbmc_project/inventory/system/chassis/motherboard/vdd_vrm0",
    "DESCRIPTION": "ECC check failed",
    "ECC DATA OF THE FAILED RECORD": "0x0285B167149C994565955944FA20377927BB62414642063B34446AA78360B5DF2D483B66",
    "RECORD DATA FOR WHICH THE ECC FAILED": "0x848C0052540456494E4944521043500020504F5745522043415244202043450131565A023031464E0746313930383237504E07504E3132333435534E0C714C32453332303130303030434304324533324845043030303143540410EB020548570200014233060000000000004234010042370C000000000000000000000000464704564E475254530100504602000078",
    "RECORD FOR WHICH THE ECC FAILED": "VINI"
}
}

Signed-off-by: PriyangaRamasamy <priyanga24@in.ibm.com>
Change-Id: I41f237e7c60eba6afcf71d8197778768607a9e6c